/*
 * This file is generated by jOOQ.
 */
package app.repository.jooq_repo;


import app.repository.jooq_repo.tables.Todos;


/**
 * Convenience access to all tables in todo-db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>todo-db.todos</code>.
     */
    public static final Todos TODOS = Todos.TODOS;
}
